language: cpp
sudo: true

os:
- linux
#- osx


compiler: 
- clang++
#- gcc
#- g++

addons:
 apt:
  sources:
  - boost-latest
  packages:
   - cmake
   - libboost-all-dev
   - libopencv-dev

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; if ! [[ `brew ls --versions boost` ]]; then brew install boost; fi; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if ! [[ `brew ls --versions gcc` ]]; then brew install gcc; fi; fi
 - gcc --version
 - g++ --version
 - clang --version
 - clang++ --version

script:
- mkdir -p build
- cd build
- cmake -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_VERBOSE_MAKEFILE=ON ..
- make -j2
- ./lib/tests
  #- ./app/mousetrack
