language: cpp
sudo: true

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - libboost-all-dev
            - libopencv-dev
            - libeigen3-dev
            - libpng12-dev
            - g++-4.9 # support for regex
        env: 
          - MATRIX_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9


before_install:
 - eval "${MATRIX_EVAL}" # Does not work for the moment
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; if ! [[ `brew ls --versions boost` ]]; then brew install boost; fi; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then if ! [[ `brew ls --versions gcc` ]]; then brew install gcc; fi; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get upgrade && echo yey!; fi
 - gcc --version
 - g++ --version
 - clang --version
 - clang++ --version


script:
- mkdir -p build
- cd build
- CC=gcc-4.9 CXX=g++-4.9 cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_GUI=NO ..
- make
- ../run_tests.sh
- ./app/mousetrack
